name: sevenxt
description: Fluttersevenxt is a premium E-commerce UI kit that you can use to build various e-commerce apps using Flutter that works on both Android & iOS. This kit contains 100+ nicely crafted minimal screens that cover everything you need for your sevenxt app.

publish_to: "none"

version: 1.1.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.11
  http: ^1.2.1
  flutter_svg: ^2.0.10+1
  form_field_validator: ^1.1.0
  cached_network_image: ^3.2.0
  flutter_rating_bar: ^4.0.1
  flutter_widget_from_html_core: ^0.15.1
  flutter_launcher_icons: ^0.13.1
  animations: ^2.0.11
  url_launcher: ^6.3.0
  file_picker: ^10.3.7
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  razorpay_flutter: ^1.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/Illustration/
    - assets/logo/
    - assets/screens/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
flutter_launcher_icons:
    android: true
    ios: true
    windows: {}
    macos: {}
    linux: {}
    chrome: {}
    image_path: "assets/logo/sevenxt.png"
    adaptive_icon_background: "#FFFFFF"
    adaptive_icon_foreground: "assets/logo/sevenxt.png"